"""Initial migration

Revision ID: 9cde68723353
Revises: 21f60fedda95
Create Date: 2024-05-15 13:25:25.279012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '9cde68723353'
down_revision = '21f60fedda95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('subjects')
    op.drop_table('employees')
    op.alter_column('attendance', 'in_time',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('attendance', 'working_hours',
               existing_type=mssql.TIME(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('attendance', 'subject',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=120),
               nullable=True)
    op.drop_constraint('FK_Attendance_Employee', 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'employee', ['employee_id'], ['id'])
    op.alter_column('timetable', 'subject',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timetable', 'subject',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key('FK_Attendance_Employee', 'attendance', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.alter_column('attendance', 'subject',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('attendance', 'working_hours',
               existing_type=sa.Float(),
               type_=mssql.TIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('attendance', 'in_time',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('card_id', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), server_default=sa.text('(NULL)'), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), server_default=sa.text('(NULL)'), autoincrement=False, nullable=True),
    sa.Column('is_admin', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__employee__3213E83FAE6B5FEC')
    )
    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('subject_name', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('start_time', mssql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', mssql.TIME(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__subjects__3213E83FABE995D1')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
